version: "3.8"

services:
  dns-server:
    image: jpillora/dnsmasq:latest
    ports:
        - "53:53/udp"
        # - 10008:8080
    environment:
      - HTTP_USER=root
      - HTTP_PASS=root
    volumes:
      - ./config/dnsmasq.conf:/etc/dnsmasq.conf
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.dns_0.middlewares=https-redirect@file"
      - "traefik.http.routers.dns_0.entrypoints=http"
      - "traefik.http.routers.dns_0.rule=Host(`dns.dev.io`)"
      - "traefik.http.routers.dns_1.middlewares=content-compress@file"
      - "traefik.http.routers.dns_1.entrypoints=https"
      - "traefik.http.routers.dns_1.tls=true"
      - "traefik.http.routers.dns_1.rule=Host(`dns.dev.io`)"
      - "traefik.http.services.dns_backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.dns_backend.loadbalancer.server.port=8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  traefik:
    external: true
