version: "3.8"

services:
  dns-server:
    image: soulteary/go-dnsmasq:test
    networks:
      - traefik
    command: dnsmasq -l 0.0.0.0:53 -f /hosts.conf -p 1s -n 114.114.114.114:53 -n 8.8.8.8:53
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./config/hosts.conf:/hosts.conf:rw
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  traefik:
    external: true