version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2021-04-22T15-44-28Z
    volumes:
      - ./data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASS}
    command: server /data
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.oss_0.middlewares=https-redirect@file"
      - "traefik.http.routers.oss_0.entrypoints=http"
      - "traefik.http.routers.oss_0.rule=Host(`${MINIO_DOMAIN}`)"
      - "traefik.http.routers.oss_1.middlewares=content-compress@file"
      - "traefik.http.routers.oss_1.entrypoints=https"
      - "traefik.http.routers.oss_1.tls=true"
      - "traefik.http.routers.oss_1.rule=Host(`${MINIO_DOMAIN}`)"
      - "traefik.http.services.oss_backend.loadbalancer.server.scheme=http"
      - "traefik.http.services.oss_backend.loadbalancer.server.port=9000"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
        interval: 30s
        timeout: 20s
        retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
networks:
  traefik:
    external: true
